"""telegram notification

Revision ID: 11b8a1f9d1bf
Revises: 7a59e4dd87ce
Create Date: 2025-04-13 11:39:01.152050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b8a1f9d1bf'
down_revision: Union[str, None] = '7a59e4dd87ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_settings', sa.Column('telegram_id', sa.String(), nullable=True))
    op.alter_column('notification_settings', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_settings', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('notification_settings', 'telegram_id')
    # ### end Alembic commands ###
