"""empty message

Revision ID: 711bbbd98750
Revises: c19b847baafb
Create Date: 2025-04-12 00:16:42.324077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711bbbd98750'
down_revision: Union[str, None] = 'c19b847baafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_products', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'monitored_products', 'products', ['product_id'], ['id'])
    op.drop_column('monitored_products', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_products', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'monitored_products', type_='foreignkey')
    op.drop_column('monitored_products', 'product_id')
    # ### end Alembic commands ###
