"""empty message

Revision ID: 7a59e4dd87ce
Revises: ed844482915e
Create Date: 2025-04-12 23:39:48.968966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a59e4dd87ce'
down_revision: Union[str, None] = 'ed844482915e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitored_products', 'url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitored_products', 'url',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###
