"""empty message

Revision ID: d32dd831ace4
Revises: 46dca963b0d6
Create Date: 2025-04-12 11:34:48.045480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32dd831ace4'
down_revision: Union[str, None] = '46dca963b0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('monitored_product_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('time_ship', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('datetime_ship', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('geo', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'products', 'monitored_products', ['monitored_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'geo')
    op.drop_column('products', 'datetime_ship')
    op.drop_column('products', 'time_ship')
    op.drop_column('products', 'monitored_product_id')
    # ### end Alembic commands ###
