"""empty message

Revision ID: f797728c180c
Revises: 711bbbd98750
Create Date: 2025-04-12 01:12:00.350610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f797728c180c'
down_revision: Union[str, None] = '711bbbd98750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_products', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('monitored_products_product_id_fkey', 'monitored_products', type_='foreignkey')
    op.drop_column('monitored_products', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_products', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('monitored_products_product_id_fkey', 'monitored_products', 'products', ['product_id'], ['id'])
    op.drop_column('monitored_products', 'name')
    # ### end Alembic commands ###
