"""empty message

Revision ID: fe6781855862
Revises: c1375a84dbe6
Create Date: 2025-04-12 17:30:37.443941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6781855862'
down_revision: Union[str, None] = 'c1375a84dbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'item_id',
               existing_type=sa.String(length=255),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
